[package]
name = "serde-queue"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.198" }
postcard = { version = "^1.0.8", features = ["use-std"] }
